### ISSUE TITLE
smooth the landing process

### ISSUE THREAD

**Issue by ednarb29** [ednarb29/Cooperative-Height-Control#10]

**Comment by ednarb29** [comment]
@SgtBlack

**Comment by SgtBlack** [comment]
Is that the requirement for an implementation in C??

**Comment by ednarb29** [comment]
I think we should do everything in C because the flight plans do not allow complex implementations.

**Comment by ednarb29** [comment]
Furthermore I think we should implement the landing till 25 cm with the height sensor. For smaller (not correct measured) heights we should implement somethink time based.

**Comment by ednarb29** [comment]
Probably we can implement the landing till 25 cm with the flight plan and only the rest in C. That should makes it a bit easier?

**Comment by SgtBlack** [comment]
Everything in C should be possible and not so much effort!

**Comment by ednarb29** [comment]
I think we should cancel this task. It is nothing which is needed for our project - if we have enough time later we can reactivate it.
