### ISSUE TITLE
create the slides

### ISSUE THREAD

**Issue by ednarb29** [ednarb29/Cooperative-Height-Control#22]

**Comment by ednarb29** [comment]
@kanwaljahan and @SgtBlack Is it okay that you both create the slides and Jawad and I will hold the talk?

**Comment by kanwaljahan** [comment]
That is ok with me.

Regards,
Kanwal Jahan

**Comment by ednarb29** [comment]
The deadline for this task is the 09.07.2015.

**Comment by kanwaljahan** [comment]
Ok, sounds great.

**Comment by ednarb29** [comment]
done
