### ISSUE TITLE
doc: ch 5 - finite state machine

### ISSUE THREAD

**Issue by ednarb29** [ednarb29/Cooperative-Height-Control#29]

**Comment by SgtBlack** [comment]
i will do this

**Comment by ednarb29** [comment]
than you also have to assign this issue to yourself ;)

**Comment by SgtBlack** [comment]
thanks

**Comment by ednarb29** [comment]
The deadline for this task is the 02.07.2015.

**Comment by ednarb29** [comment]
Please think of finishing and upload the task this week.
