### ISSUE TITLE
write a simple oscillation process in c

### ISSUE THREAD

**Issue by ednarb29** [ednarb29/Cooperative-Height-Control#9]
as you said you will have a look to this.

**Comment by ednarb29** [comment]
stupid stuff! Why I can not assign more than one people to this task? Does someone knows more than me? ;)

**Comment by ednarb29** [comment]
@kanwaljahan

**Comment by ednarb29** [comment]
I think oscillation between 50 and 100 cm is enough. So we should surely stay in a well measured area.

**Comment by kahlonel** [comment]
GitHub assumes we are good enough to handle tasks alone haha :smile: 
You're right about the oscillation range. Should keep 'margin of safety' in our upper/lower limits.

**Comment by ednarb29** [comment]
What is the current status of this task?

**Comment by ednarb29** [comment]
If you have some things done commit it please so that everyone can have a look.

**Comment by kahlonel** [comment]
I have done some additions, but need to test them before I commit.

**Comment by ednarb29** [comment]
Fabian and I have written now a tested and working oscillation process. So we can concentrate now on holding the height of an obstacle.

**Comment by ednarb29** [comment]
(it is committed)
